name: CI

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: npm ci

      - name: test
        run: npm run test

      - name: linter
        run: make lint